output_dir: /data/crstatic/public_html/blog
template_dir: /data/crstatic/templates/
templates:
  archive: archive.html
  post: blog.html
  feed: feed.xml
  sitemap: sitemap.xml
post_dir: /data/crstatic/blog/articles
site_name: CloudRoutes Blog
site_description: Automate incident response and let your Devops team sleep at night
site_shortdesc: Automated incident response
site_thumbnail: https://cloudrout.es/static/img/cloudroutes-mini-super.png
site_url: https://cloudrout.es/blog
site_feed: https://feed.cloudrout.es
site_keywords: 
  - Monitoring Automation
  - Cloud Monitoring
  - Incident Response
  - Application Monitoring
  - Server Monitoring
  - Cloud Monitoring
  - DNS Failover
  - CloudFlare DNS Failover
  - Monitoring Automation
  - Startup Blog
  - Engineering Blog
site_author: CloudRoutes
site_authorlink: https://twitter.com/cloudroutes
